import assert from "node:assert/strict";
import test from "node:test";
import type { TaskConversationDetail } from "../shared/taskConversationTypes.js";
import { TaskConversationProjectionCache } from "./tasks/taskConversationProjectionCache.js";

const detail=(threadId:string,text="ok"):TaskConversationDetail=>({conversation:{taskId:"task",threadId,displayName:threadId,isPrimary:false,archived:false,remoteSyncState:"synced",createdAt:"2026-01-01T00:00:00Z",updatedAt:"2026-01-01T00:00:00Z",preview:"",status:"idle",cwd:"C:/task",modelProvider:"openai"},turns:[{id:"turn",status:"completed",items:[{kind:"assistant",id:"item",text}]}]});

test("shares concurrent misses and serves warm projections without reloading",async()=>{const cache=new TaskConversationProjectionCache();let loads=0;const loader=async()=>{loads+=1;await Promise.resolve();return detail("thread")};const [a,b]=await Promise.all([cache.get("task","thread",loader),cache.get("task","thread",loader)]);assert.equal(a,b);await cache.get("task","thread",loader);assert.equal(loads,1);});
test("expires, invalidates and evicts least-recent projections",async()=>{let clock=0;const cache=new TaskConversationProjectionCache({maxEntries:2,ttlMs:10,now:()=>clock});let loads=0;const load=(id:string)=>cache.get("task",id,async()=>{loads+=1;return detail(id)});await load("a");await load("b");await load("a");await load("c");await load("b");assert.equal(loads,4);cache.invalidate("task","a");await load("a");clock=20;await load("a");assert.equal(loads,6);});
test("does not retain an oversized projection",async()=>{const cache=new TaskConversationProjectionCache({maxEntryBytes:64});let loads=0;const loader=async()=>{loads+=1;return detail("large","x".repeat(1000))};await cache.get("task","large",loader);await cache.get("task","large",loader);assert.equal(loads,2);assert.equal(cache.stats().entries,0);});

test("does not reuse or repopulate an in-flight projection after invalidation",async()=>{const cache=new TaskConversationProjectionCache();let releaseFirst:((value:TaskConversationDetail)=>void)|undefined;let loads=0;const first=cache.get("task","thread",()=>{loads+=1;return new Promise<TaskConversationDetail>((resolve)=>{releaseFirst=resolve;});});await Promise.resolve();cache.invalidate("task","thread");const second=cache.get("task","thread",async()=>{loads+=1;return detail("thread","fresh")});assert.equal((await second).turns[0].items[0].kind,"assistant");assert.equal(loads,2);releaseFirst?.(detail("thread","stale"));await first;const warm=await cache.get("task","thread",async()=>{loads+=1;return detail("thread","unexpected")});assert.equal((warm.turns[0].items[0] as {text:string}).text,"fresh");assert.equal(loads,2);});
