import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import type { Server } from "node:http";
import express from "express";
import { chromium, expect } from "@playwright/test";
import { TaskStore } from "../../src/server/tasks/taskStore.js";
import { TaskConversationService } from "../../src/server/tasks/taskConversationService.js";
import { CodexRpcError } from "../../src/server/codexAppServerClient.js";
import { TaskModeService } from "../../src/server/tasks/taskModeService.js";
import { createTaskRouter } from "../../src/server/tasks/taskRouter.js";
import { createTaskModeRouter } from "../../src/server/tasks/taskModeRouter.js";
import type { CodexConversationManager } from "../../src/server/codexConversationManager.js";
import { DEFAULT_TASK_MODE_SETTINGS } from "../../src/shared/taskModeTypes.js";
import { ControlledExecutor, directOutput } from "../fixtures/taskModeQuickExecutor.js";

test("settings, task creation, and the top authorization button use durable authorization contracts", {timeout:90000}, async()=>{
  const build=path.resolve(process.env.TASK_MODE_LOADING_BUILD_DIR??".local-test-data/auth-loading-release/task-monitor-client");
  assert.ok(fs.existsSync(path.join(build,"task-monitor.html")));
  const directory=fs.mkdtempSync(path.join(os.tmpdir(),"apron-auth-ui-"));
  const store=new TaskStore(directory),manager=new ControlledExecutor();
  const conversations=new TaskConversationService(store,manager as unknown as CodexConversationManager),mode=new TaskModeService(conversations,{pollMs:50});
  mode.data.saveSettings({...DEFAULT_TASK_MODE_SETTINGS,executionMode:"quick"});
  const acceptanceTask=store.create({title:"结果待人工验收",descriptionMd:"实施完成，等待验收结果",repositoryPath:directory,status:"pending_manual_acceptance"});
  const app=express();app.use(express.json());app.use((_req,res,next)=>{res.locals.user={name:"authorization-test",method:"none"};next();});
  app.get("/api/me",(_req,res)=>res.json({name:"authorization-test",method:"none"}));
  app.get("/api/auth/config",(_req,res)=>res.json({methods:["none"],user:"authorization-test"}));
  app.use("/api/tasks",createTaskRouter(async()=>store));app.use("/api/task-mode",createTaskModeRouter(async()=>mode));
  app.use("/task-monitor",express.static(build,{dotfiles:"allow"}));app.get("/task-monitor/",(_req,res)=>res.sendFile(path.join(build,"task-monitor.html"),{dotfiles:"allow"}));
  let server:Server|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
  try{
    server=await new Promise<Server>(resolve=>{const next=app.listen(0,"127.0.0.1",()=>resolve(next));});
    const origin=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
    browser=await chromium.launch({headless:true,channel:"msedge"});
    const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[];
    page.on("pageerror",error=>errors.push(error.message));
    const evidenceReads={changes:0,items:0};page.on("request",request=>{if(request.url().endsWith("/changes"))evidenceReads.changes++;if(request.url().endsWith("/items"))evidenceReads.items++;});
    await page.goto(`${origin}/task-monitor/?mode=task-mode`);
    await page.getByRole("button",{name:"代理设置",exact:true}).click();
    await page.getByLabel("授权类型",{exact:true}).selectOption("full_authorization");
    await page.getByRole("button",{name:"保存设置",exact:true}).click();
    await expect(page.getByRole("status").filter({hasText:"设置已保存到服务器"})).toBeVisible();
    assert.equal(mode.data.settings().authorizationType,"full_authorization");
    assert.equal(mode.data.settings().permissionPreset,"full_access");
    await page.locator(".tp-sidebar").getByRole("button",{name:"任务板",exact:false}).click();
    await page.getByRole("button",{name:"新建任务",exact:true}).first().click();
    await page.getByLabel("任务名称",{exact:true}).fill("UI 授权路径");
    await page.locator(".ra-layout .tiptap").first().fill("修改指定配置并验证");
    await page.getByLabel("项目工作目录",{exact:true}).fill(directory);
    await page.getByLabel("授权类型",{exact:true}).selectOption("pending_approval");
    await page.getByRole("button",{name:"保存任务",exact:true}).click();
    await expect(page.getByRole("heading",{name:"UI 授权路径",exact:true})).toBeVisible();
    const task=store.list().tasks.find(item=>item.title==="UI 授权路径")!;manager.taskId=task.id;
    assert.equal(mode.detail(task.id).state.settings.authorizationType,"pending_approval");
    await expect(page.getByLabel("发送指示授权类型")).toHaveValue("pending_approval");
    await page.getByRole("button",{name:"开始执行",exact:true}).click();
    await expect.poll(()=>mode.detail(task.id).state.runs.at(-1)?.jobs.find(job=>job.status==="active")?.id).toBeTruthy();
    const job=mode.detail(task.id).state.runs.at(-1)!.jobs.find(job=>job.status==="active")!;
    manager.complete(job,directOutput({status:"blocked",acceptanceReady:false,pauseCategory:"authorization",stopReason:"等待指定配置的修改授权",humanActions:[{action:"批准修改 config.json",reason:"配置修改需要授权",unblocks:"修改并验证 config.json"}],remainingWork:["修改并验证 config.json"]}));
    const approve=page.getByRole("button",{name:"批准授权",exact:true});
    await expect(approve).toBeVisible();
    const contents=page.getByRole("region",{name:"具体需要授权的内容"});
    await expect(contents).toContainText("批准修改 config.json");
    await expect(page.locator(".tp-detail-heading .tp-status")).toContainText("待确认");
    assert.notEqual(store.get(task.id)!.status,"blocked");
    const buttonBox=await approve.boundingBox(),contentBox=await contents.boundingBox();
    assert.ok(buttonBox&&contentBox&&buttonBox.y<contentBox.y,"approval button is above the request details");
    fs.mkdirSync(".local-test-data/auth-loading-evidence",{recursive:true});
    await page.screenshot({path:".local-test-data/auth-loading-evidence/awaiting-authorization.png",fullPage:true});
    await expect(page.locator(".tp-detail-heading .tp-status")).toHaveAttribute("data-status","confirmation");
    await page.getByRole("button",{name:"返回任务板",exact:true}).click();
    const reviewColumn=page.locator('[data-column="pending_manual_acceptance"]');
    await expect(reviewColumn.locator(".tp-column-head")).toContainText("待确认 / 待验收");
    await expect(reviewColumn.locator("[data-task-id]")).toHaveCount(2);
    await expect(reviewColumn.locator(`[data-task-id="${task.id}"] .tp-status`)).toHaveText("待确认");
    await expect(reviewColumn.locator(`[data-task-id="${acceptanceTask.id}"] .tp-status`)).toHaveText("待验收");
    await expect(page.locator('[data-column="awaiting_authorization"]')).toHaveCount(0);
    await page.screenshot({path:".local-test-data/auth-loading-evidence/confirmation-acceptance-board.png",fullPage:true});
    await reviewColumn.locator(`[data-task-id="${task.id}"]`).click();
    await expect(approve).toBeVisible();
    const runId=mode.detail(task.id).state.activeRunId;
    await approve.click();
    await expect.poll(()=>mode.detail(task.id).state.runs.at(-1)?.jobs.find(next=>next.id!==job.id&&next.status==="active")?.id).toBeTruthy();
    const continued=mode.detail(task.id).state.runs.at(-1)!.jobs.find(next=>next.id!==job.id&&next.status==="active")!;
    assert.equal(mode.detail(task.id).state.activeRunId,runId);
    assert.match(continued.text,/批准修改 config.json/);
    manager.threads.get(continued.threadId!)!.turns.find((turn:any)=>turn.id===continued.turnId)!.items.push({id:"deferred-file-change",type:"fileChange",status:"completed",changes:[{path:"config.json",diff:"DEFERRED-DIFF-EVIDENCE"}]});
    manager.complete(continued,directOutput({status:"needs_confirmation",changedFiles:["config.json"],stopReason:"本轮已达到验收条件，等待人工验收"}));
    await expect(approve).toHaveCount(0);
    await expect(page.locator(".tp-detail-heading .tp-status")).toHaveText("待验收");
    await expect(page.locator(".tp-detail-heading .tp-status")).toHaveAttribute("data-status","acceptance");
    assert.equal(evidenceReads.changes,0);assert.equal(evidenceReads.items,0);
    await page.locator(".tm-report-changes > summary").click();
    await expect(page.getByText("DEFERRED-DIFF-EVIDENCE",{exact:true})).toBeVisible();
    assert.equal(evidenceReads.changes,1);
    await page.getByRole("button",{name:"全部活动",exact:true}).click();
    await page.locator(".tp-feed > details > summary").nth(1).click();
    await expect(page.getByText("修改文件：config.json",{exact:true})).toBeVisible();
    assert.equal(evidenceReads.items,1);
    await page.getByRole("button",{name:/^需求与执行/}).click();
    await page.getByRole("button",{name:"验收通过",exact:true}).click();
    await expect.poll(()=>mode.detail(task.id).state.phase).toBe("completed");
    // Reproduce an occupied old writer after completion through the actual UI submission.
    const sourceThreadId=continued.threadId!,request=manager.request.bind(manager);
    manager.request=async(method:string,params:any)=>{
      if(method==="thread/resume"&&params.threadId===sourceThreadId){manager.calls.push({method,params});throw new CodexRpcError(`thread ${sourceThreadId} already has an active writer`);}
      if(method==="thread/fork"){
        manager.calls.push({method,params});const source=manager.threads.get(params.threadId)!;
        const fork={...structuredClone(source),id:`recovered-fork-${++manager.sequence}`,cwd:params.cwd,status:{type:"idle"}};manager.threads.set(fork.id,fork);return {thread:fork};
      }
      return request(method,params);
    };
    await page.getByRole("textbox",{name:"下一步指示",exact:true}).fill("完成后只补充新的验收要求");
    await page.getByRole("button",{name:"发送给代理",exact:true}).click();
    await expect.poll(()=>mode.detail(task.id).state.runs.length).toBe(2);
    await expect.poll(()=>mode.detail(task.id).state.runs[1].jobs.find(job=>job.status==="active")?.id).toBeTruthy();
    const followup=mode.detail(task.id).state.runs[1].jobs.find(job=>job.status==="active")!;
    assert.equal(followup.recoveredFromThreadId,sourceThreadId);assert.notEqual(followup.threadId,sourceThreadId);
    assert.equal(manager.calls.filter(call=>call.method==="thread/fork").length,1);
    assert.equal(mode.detail(task.id).state.runs[0].result!.status,"done");
    await expect(page.locator(".tp-detail-heading .tp-status")).toHaveText("进行中");
    assert.notEqual(mode.detail(task.id).state.heartbeat.status,"needs_attention");
    manager.complete(followup,directOutput());
    await expect.poll(()=>mode.detail(task.id).state.phase).toBe("completed");
    assert.equal(mode.detail(task.id).state.instructions.length,2);
    assert.deepEqual(errors,[]);
  }finally{
    await browser?.close();server?.closeAllConnections();await new Promise<void>(resolve=>server?server.close(()=>resolve()):resolve());
    mode.close();conversations.close();store.close();
  }
});
